stages:
  - build-testing-image
  - unit-test
  - test

    
# Build the tox image (which is used to test the hep-score package)
# Use new CERN ci-tools (July 2019, BMK-113): see https://cern.service-now.com/service-portal/article.do?n=KB0005851
# Adapted from https://gitlab.cern.ch/gitlabci-examples/build_docker_image/blob/master/.gitlab-ci.yml
# Kaniko is the recommended method for running Docker-builds as of May 2019. 
# See https://docs.gitlab.com/ee/ci/docker/using_kaniko.html for GitLab's documentation.
job_build_image_tox:
  stage: build-testing-image
  image: # NB enable shared runners and do not specify a CI tag
    name: gitlab-registry.cern.ch/ci-tools/docker-image-builder # CERN version of the Kaniko image
    entrypoint: [""]
  only:
    refs:
    - qa
    changes:
    - docker-images/tox/*
  script:
    # Prepare Kaniko configuration file
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    # Build and push the image from the Dockerfile at the root of the project.
    # To push to a specific docker tag, amend the --destination parameter, e.g. --destination $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
    # See https://docs.gitlab.com/ee/ci/variables/predefined_variables.html#variables-reference for available variables
    - /kaniko/executor --context $CI_PROJECT_DIR/docker-images/tox --dockerfile $CI_PROJECT_DIR/docker-images/tox/Dockerfile --destination $CI_REGISTRY_IMAGE/tox:latest

.pep8:
  stage: unit-test
  image: gitlab-registry.cern.ch/hep-benchmarks/hep-score/tox
  except:
    - tags
  script:
    - yum install openldap-devel krb5-devel -y
    - cd $CI_PROJECT_DIR
    - scl enable rh-python35 'tox -epep8'

python27:
  stage: unit-test
  image: gitlab-registry.cern.ch/hep-benchmarks/hep-score/tox
  except:
    - tags
  script:
    - yum install openldap-devel krb5-devel mysql-devel -y
    - cd $CI_PROJECT_DIR
    - tox -epy27

coverage:
  stage: unit-test
  image: gitlab-registry.cern.ch/hep-benchmarks/hep-score/tox
  except:
    - tags
  script:
    - yum install openldap-devel krb5-devel mysql-devel -y
    - cd $CI_PROJECT_DIR
    - scl enable rh-python35 'tox -ecover'
  artifacts:
    paths:
      - cover

job_test_kv_run_cc7:
    image: gitlab-registry.cern.ch/hep-benchmarks/hep-benchmark-suite/hep-benchmark-suite-cc7:latest
    tags:
        -  hep-score-docker-runner 
    stage: test
    script: 
        - yum install -y yum-plugin-ovl #because of https://github.com/CentOS/sig-cloud-instance-images/issues/15
        - echo "install hepscore"
        - pip install .
        - echo "create working dir"
        - mkdir -p /tmp/HEPSCORE/$CI_JOB_ID
        - echo "test the configuration dump"
        - hep-score -p -f $CI_PROJECT_DIR/hepscore/tests/etc/hepscore_conf_ci.yaml /tmp/HEPSCORE/$CI_JOB_ID
        - export TESTDIR=$CI_PROJECT_DIR/hepscore/tests
        - echo "test the parsing of existing wl results"
        - $TESTDIR/mock_hepscore.py $TESTDIR/etc/hepscore_conf_ci.yaml $TESTDIR/data/HEPscore_ci/
        - echo "test run of hep-score with configuration for atlas-kv-bmk"
        - hep-score -d -f $CI_PROJECT_DIR/hepscore/tests/etc/hepscore_conf_ci.yaml /tmp/HEPSCORE/$CI_JOB_ID
    after_script:
        - tar -czf hep-score-test.tgz /tmp/HEPSCORE/$CI_JOB_ID	
    only:
      refs:
        - qa
    artifacts:
        paths:
           - hep-score-test.tgz
        expire_in: 1 week
        when: always
